#!/bin/bash

#Viskas korralikult üle, virtukas klaviatuur paigast ära

curl http://x-road.eu/packages/xroad_repo.gpg| sudo apt-key add -
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 00A6F0A3C300EE8C
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EB9B1D8886F44E2A

#Paigaldan turva serveri paketid

sudo apt-get update
sudo apt-get install xroad-securityserver


